package com.projectonecs320.Suppliers;

import java.util.function.Supplier;

import com.projectonecs320.Classes.Appointment;
import com.projectonecs320.Services.AppointmentService;

/**
 * Supplies Appointment objects with unique IDs generated by an AppointmentService.
 */
public class AppointmentSupplier implements Supplier<Appointment> {

    private AppointmentService appointmentService;

    /**
     * Constructs an AppointmentSupplier with the specified AppointmentService.
     * 
     * @param appointmentService The AppointmentService used to generate unique IDs for appointments.
     */
    public AppointmentSupplier(AppointmentService appointmentService) {
        this.appointmentService = appointmentService;
    }
    
    /**
     * Generates a new Appointment object with a unique ID generated by the AppointmentService.
     * 
     * @return A new Appointment object with a unique ID.
     */
    @Override
    public Appointment get() {
        return new Appointment(appointmentService.generateId());
    }
    
}
