package com.projectonecs320.Suppliers;

import java.util.function.Supplier;

import com.projectonecs320.Classes.Contact;
import com.projectonecs320.Services.ContactService;

/**
 * Supplies Contact objects with unique IDs generated by a ContactService.
 */
public class ContactSupplier implements Supplier<Contact> {

    private ContactService contactService;

    /**
     * Constructs a ContactSupplier with the specified ContactService.
     * 
     * @param contactService The ContactService used to generate unique IDs for contacts.
     */
    public ContactSupplier(ContactService contactService) {
        this.contactService = contactService;
    }
    
    /**
     * Generates a new Contact object with a unique ID generated by the ContactService.
     * 
     * @return A new Contact object with a unique ID.
     */
    @Override
    public Contact get() {
        return new Contact(contactService.generateId());
    }
    
}
