package com.projectonecs320.Suppliers;

import java.util.function.Supplier;

import com.projectonecs320.Classes.Task;
import com.projectonecs320.Services.TaskService;

/**
 * Supplies Task objects with unique IDs generated by a TaskService.
 */
public class TaskSupplier implements Supplier<Task> {

    private TaskService taskService;

    /**
     * Constructs a TaskSupplier with the specified TaskService.
     * 
     * @param taskService The TaskService used to generate unique IDs for tasks.
     */
    public TaskSupplier(TaskService taskService) {
        this.taskService = taskService;
    }
    
    /**
     * Generates a new Task object with a unique ID generated by the TaskService.
     * 
     * @return A new Task object with a unique ID.
     */
    @Override
    public Task get() {
        return new Task(taskService.generateId());
    }
    
}
